services:
  config-server:
    image: postgres:latest
    restart: unless-stopped
    container_name: config-server
    hostname: pg-config-server
    environment:
      POSTGRES_DB: ${CONFIGSERVER_PG_DATABASE:-config_db}
      POSTGRES_USER: ${CONFIGSERVER_PG_USERNAME:-config_user}
      POSTGRES_PASSWORD: ${CONFIGSERVER_PG_PASSWORD:-config_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_config_data:/var/lib/postgresql/data
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U config_user -d config_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: postgres:latest
    restart: unless-stopped
    container_name: auth-service
    hostname: pg-auth-service
    environment:
      POSTGRES_DB: ${AUTHSERVICE_PG_DATABASE:-auth_db}
      POSTGRES_USER: ${AUTHSERVICE_PG_USERNAME:-auth_user}
      POSTGRES_PASSWORD: ${AUTHSERVICE_PG_PASSWORD:-auth_pass}
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client-service:
    image: postgres:latest
    restart: unless-stopped
    container_name: client-service
    hostname: pg-client-service
    environment:
      POSTGRES_DB: ${CLIENTSERVICE_PG_DATABASE:-client_db}
      POSTGRES_USER: ${CLIENTSERVICE_PG_USERNAME:-client_user}
      POSTGRES_PASSWORD: ${CLIENTSERVICE_PG_PASSWORD:-client_pass}
    ports:
      - "5434:5432"
    volumes:
      - postgres_client_data:/var/lib/postgresql/data
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U client_user -d client_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  etldata-service:
    image: postgres:latest
    restart: unless-stopped
    container_name: etldata-service
    hostname: pg-etldata-service
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${ETLDATASERVICE_PG_DATABASE:-etldata_db}
      POSTGRES_USER: ${ETLDATASERVICE_PG_USERNAME:-etldata_user}
      POSTGRES_PASSWORD: ${ETLDATASERVICE_PG_PASSWORD:-etldata_pass}
    ports:
      - "5435:5432"
    volumes:
      - postgres_etl_data:/var/lib/postgresql/data
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  search-service:
    image: postgres:latest
    restart: unless-stopped
    container_name: search-service
    hostname: pg-search-service
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${SEARCHSERVICE_PG_DATABASE:-search_db}
      POSTGRES_USER: ${SEARCHSERVICE_PG_USERNAME:-search_user}
      POSTGRES_PASSWORD: ${SEARCHSERVICE_PG_PASSWORD:-search_pass}
    ports:
      - "5436:5432"
    volumes:
      - postgres_search_data:/var/lib/postgresql/data
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  s3minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: s3minio
    restart: unless-stopped
    hostname: s3minio
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD:-password123}
      MINIO_REGION: ${S3_REGION:-ru-moscow-1}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - s3minio_data:/data
      - s3minio-config:/root/.minio
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.1.3-management
    restart: unless-stopped
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VIRTUAL_HOST:-/}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - pricat-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.6
    restart: unless-stopped
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.6
    restart: unless-stopped
    container_name: kibana
    hostname: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - pricat-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  postgres_config_data:
  postgres_auth_data:
  postgres_client_data:
  postgres_etl_data:
  postgres_search_data:
  s3minio_data:
  s3minio-config:
  rabbitmq_data:
  es-data:

networks:
  pricat-network:
    name: pricat-network
    driver: bridge